# Generated by Django 5.1.2 on 2024-10-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_articleembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('polarized_content', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processed', 'Processed Successfully'), ('skipped', 'Skipped (Too Long)')], default='processed', max_length=10)),
            ],
        ),
    ]
